### ISSUE TITLE
标注里没有landmark的框loss部分有做处理吗？

### ISSUE THREAD

**Issue by changhy666** [derronqi/yolov8-face#6]
如题，新的yolov8face针对没有landmark框有做什么特别的处理吗？
我看代码里加载的模型是pose的，标注分3列，应该是x，y和visible，感觉没landm信息的可以通过visible决定是否计算loss，我用的yolov5face标注里是把没有landmark的框置为-1的，但是似乎v8不允许这种标注存在。
![image](https://github.com/derronqi/yolov8-face/assets/57101883/1f111b6c-02e3-45be-9f17-b63f6605831b)

**Comment by derronqi** [comment]
把visible置为0
